### ISSUE TITLE
Parallem imm runs for a long time

### ISSUE THREAD

**Issue by xindubawukong** [pnnl/ripples#5]
Here's the command I run:
`./build/release/tools/imm -i ./edgelists/HepPh_sym-sorted-edge-list.txt -u -w --distribution normal --mean 0.1 --variance 0.0 --disable-renumbering -k 200 -p -d IC -e 0.5 -o output.txt`

Without the `-p` option, the sequential running time match the paper well. But after adding the `-p` option, it takes much time to run (much longer than sequential time).

I'm using a machine with 100 CPUs and no GPUs. And I'm sure the memory is enough for it.

Do you have any idea why the parallel imm doesn't work? @mminutoli 
Thank you very much.

**Comment by mminutoli** [comment]
You want to be careful with memory placement on such big machines.  I am expecting that the machine you are using has multiple sockets. The graph you are loading is relatively small and there is the risk that it will be stored in a single numa domain artificially creating a bottleneck.  You want to play with the OpenMP binding and placement environment variables and see how things change. With this said, HepPh is tiny and might not require the work that can justify all the threads you are throwing at it.
